### 1. Bibliotecas

In [3]:
import os
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
from IPython import display

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.tree import export_graphviz

from pandas.plotting import scatter_matrix

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

### 2. Import do Dataset

In [4]:
col_names = ['Class', 'Specimen_Number', 'Eccentricity',
             'Aspect_Radio', 'Elongation', 'Solidity',
             'Stochastic_Convexity', 'Isoperimetric_Factor', 'Maximal_Identation_Depth',
             'Lobedness', 'Average_Intensity', 'Average_Contrast', 'Smoothness',
             'Third_Moment', 'Uniformity', 'Entropy']

#df = pd.read_csv('dados/leaf.csv', header=None, names=col_names)
df = pd.read_csv('dados/leaf.csv', header=None)

In [30]:
df.head(100)

0   1        2       3        4        5        6        7         8   \
0    1   1  0.72694  1.4742  0.32396  0.98535  1.00000  0.83592  0.004657   
1    1   2  0.74173  1.5257  0.36116  0.98152  0.99825  0.79867  0.005242   
2    1   3  0.76722  1.5725  0.38998  0.97755  1.00000  0.80812  0.007457   
3    1   4  0.73797  1.4597  0.35376  0.97566  1.00000  0.81697  0.006877   
4    1   5  0.82301  1.7707  0.44462  0.97698  1.00000  0.75493  0.007428   
5    1   6  0.72997  1.4892  0.34284  0.98755  1.00000  0.84482  0.004945   
6    1   7  0.82063  1.7529  0.44458  0.97964  0.99649  0.76770  0.005928   
7    1   8  0.77982  1.6215  0.39222  0.98512  0.99825  0.80816  0.005099   
8    1   9  0.83089  1.8199  0.45693  0.98240  1.00000  0.77106  0.006005   
9    1  10  0.90631  2.3906  0.58336  0.97683  0.99825  0.66419  0.008402   
10   1  11  0.74590  1.4927  0.34116  0.98296  1.00000  0.83088  0.005567   
11   1  12  0.79606  1.6934  0.43387  0.98181  1.00000  0.76985  0.007799   
12   2   1  0.93361  2.7582  0.64257  0.98346  1.00000  0.59851  0.005534   
13   2   2  0.91186  2.4994  0.60323  0.98300  1.00000  0.64916  0.006149   
14   2   3  0.89063  2.2927  0.56667  0.98732  1.00000  0.66427  0.002837   
15   2   4  0.86755  2.0090  0.51464  0.98691  1.00000  0.70277  0.005444   
16   2   5  0.91852  2.5247  0.61648  0.97870  1.00000  0.63037  0.005049   
17   2   6  0.88795  2.2038  0.56218  0.97835  0.99825  0.64158  0.005924   
18   2   7  0.85121  1.9548  0.48920  0.98622  1.00000  0.70267  0.003973   
19   2   8  0.89084  2.2979  0.57815  0.97389  1.00000  0.64598  0.015271   
20   2   9  0.93062  2.8973  0.65828  0.98182  1.00000  0.57950  0.006489   
21   2  10  0.84113  1.8600  0.46549  0.99039  1.00000  0.75976  0.004676   
22   3   1  0.70273  1.2099  0.36317  0.92110  0.98772  0.60555  0.023597   
23   3   2  0.66307  1.2065  0.32559  0.94952  0.99649  0.75954  0.013388   
24   3   3  0.61289  1.0991  0.33117  0.92405  0.98421  0.61661  0.025545   
25   3   4  0.70668  1.2510  0.38111  0.94226  0.99825  0.69250  0.019432   
26   3   5  0.66889  1.1435  0.38460  0.90355  0.99649  0.60571  0.028329   
27   3   6  0.50139  1.0066  0.29593  0.91585  0.99825  0.64029  0.021782   
28   3   7  0.60803  1.0646  0.34460  0.90487  0.99649  0.67517  0.031915   
29   3   8  0.56599  1.0427  0.35318  0.89086  0.99825  0.62068  0.032971   
..  ..  ..      ...     ...      ...      ...      ...      ...       ...   
70   8   1  0.98502  6.0596  0.83612  0.97628  0.98772  0.31546  0.023220   
71   8   2  0.98487  6.0229  0.83628  0.96522  1.00000  0.29509  0.024667   
72   8   3  0.98853  6.6280  0.84928  0.96861  0.97719  0.27717  0.029032   
73   8   4  0.98326  5.8308  0.82878  0.96489  1.00000  0.30777  0.014672   
74   8   5  0.98592  6.0269  0.83884  0.96027  0.96842  0.28345  0.025004   
75   8   6  0.98695  6.2904  0.84124  0.97085  1.00000  0.29288  0.023221   
76   8   7  0.98717  6.5173  0.84726  0.96846  1.00000  0.28899  0.022056   
77   8   8  0.98361  5.8719  0.82847  0.95488  0.98421  0.32134  0.040164   
78   8   9  0.98643  6.1273  0.84737  0.95274  0.89649  0.29982  0.019421   
79   8  10  0.98600  6.1763  0.83942  0.97837  0.99298  0.31607  0.011769   
80   8  11  0.98824  7.1420  0.86069  0.96683  0.99474  0.26951  0.021697   
81   9   1  0.47821  1.2059  0.34976  0.90378  0.99649  0.51298  0.030166   
82   9   2  0.53941  1.2780  0.32286  0.91793  0.97368  0.63545  0.034884   
83   9   3  0.54833  1.2733  0.31093  0.93409  0.99825  0.59707  0.017966   
84   9   4  0.58938  1.3232  0.40145  0.89009  0.98421  0.43977  0.047907   
85   9   5  0.64803  1.3920  0.41362  0.89752  0.96316  0.50892  0.026737   
86   9   6  0.54029  1.2759  0.36992  0.88831  0.97719  0.54283  0.028138   
87   9   7  0.43090  1.2825  0.38769  0.85341  0.96667  0.46204  0.052403   
88   9   8  0.46590  1.2195  0.27095  0.94433  1.00000  0.66599  0.013322   
89   9   9  0.48670  1.2165  0.37691  0.90161  0.99474  0.54006  0.032181   


In [5]:
X = df.iloc[:, 2:] # 14 feature columns
y = df.iloc[:, 0]  # 1 class column

## 3. Visualização dos Dados

## 4. Treinamento do Modelo

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rfc = RandomForestClassifier(random_state=42)

# Dictionary with parameters names (string) as keys and lists of parameter settings to try as values,
# or a list of such dictionaries, in which case the grids spanned by each dictionary in the list are explored.
# This enables searching over any sequence of parameter settings.

max_depth = [5, 10, 15, 18, 20]
max_depth.append(None)

param_grid = {
    # The number of trees in the forest
    'n_estimators': [25, 50, 100, 150, 200, 250],
    
    # The function to measure the quality of a split
    'criterion' :['gini', 'entropy'],
    
    # The maximum depth of the tree
    'max_depth' : max_depth,
    
    # The number of features to consider when looking for the best split
    'max_features': ['auto', 'sqrt', 'log2']
}

scoring = ['accuracy', 'f1_micro', 'f1_macro']

CV_rfc = GridSearchCV(estimator=rfc,
                      scoring=scoring,
                      n_jobs=-1, # Number of jobs to run in parallel (-1 == All)
                      param_grid=param_grid,
                      verbose=True,
                      refit='accuracy',
                      cv=10, # 10-Fold Cross-Validation
                      return_train_score=False)
CV_rfc.fit(X_train, y_train)

df2 = pd.DataFrame(CV_rfc.cv_results_)
df2.to_csv('resultado.csv', sep=';')

Fitting 10 folds for each of 216 candidates, totalling 2160 fits


c:\users\mathe\miniconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 6 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    2.3s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:    5.4s
[Parallel(n_jobs=-1)]: Done 426 tasks      | elapsed:   10.5s
[Parallel(n_jobs=-1)]: Done 776 tasks      | elapsed:   17.9s
[Parallel(n_jobs=-1)]: Done 1226 tasks      | elapsed:   29.3s
[Parallel(n_jobs=-1)]: Done 1776 tasks      | elapsed:   52.4s
[Parallel(n_jobs=-1)]: Done 2160 out of 2160 | elapsed:  1.2min finished
c:\users\mathe\miniconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will b

In [22]:
# Get the best parameters
print ('Best parameters:', CV_rfc.best_params_)
print ('Best Score:', CV_rfc.best_score_)

Best parameters: {'criterion': 'gini', 'max_depth': 18, 'max_features': 'auto', 'n_estimators': 200}
Best Score: 0.7904411764705882


In [23]:
rfc1=RandomForestClassifier(random_state=42,
                            max_features='auto',
                            n_estimators= 200,
                            max_depth=18,
                            criterion='gini')

In [24]:
rfc1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=18, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [25]:
y_pred=rfc1.predict(X_test)

In [26]:
print("Accuracy for Random Forest on Test data: ", accuracy_score(y_test,pred))

Accuracy for Random Forest on Test data:  0.7794117647058824


In [27]:
# Pq não aparecem as 40 classes?
print(classification_report(y_test, y_pred, digits=4))

              precision    recall  f1-score   support

           1     0.5000    0.6667    0.5714         3
           2     1.0000    1.0000    1.0000         1
           3     0.0000    0.0000    0.0000         1
           4     0.0000    0.0000    0.0000         2
           5     1.0000    1.0000    1.0000         3
           6     1.0000    1.0000    1.0000         2
           7     0.5000    1.0000    0.6667         1
           8     1.0000    1.0000    1.0000         5
           9     0.6667    0.6667    0.6667         3
          10     0.5000    1.0000    0.6667         1
          11     1.0000    1.0000    1.0000         7
          12     1.0000    0.5000    0.6667         2
          13     0.3333    0.5000    0.4000         2
          14     1.0000    0.5000    0.6667         2
          15     1.0000    1.0000    1.0000         1
          22     0.8000    0.8000    0.8000         5
          24     1.0000    1.0000    1.0000         2
          25     1.0000    

c:\users\mathe\miniconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\mathe\miniconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


## 5. Visualização dos Resultados

In [28]:
# Plot do trab. anterior não funciona bem com 40 classes
cm = confusion_matrix(y_test,pred)
classes = ['Quercus_suber','Salix_atrocinera','Populus_nigra','Alnus_sp.','Quercus_robur',
          'Crataegus_monogyna','Ilex_aquifolium','Nerium_oleander','Betula_pubescens', 'Tilia tomentosa',
          'Acer_palmatum', 'Celtis_sp.', 'Corylus_avellana','Castanea_sativa','Populus_alba',
          'Acer_negundo','Taxus_bacatta','Papaver_sp.','Polypolium_vulgare','Pinus_sp.',
          'Fraxinus_sp.','Primula_vulgaris','Erodium_sp.','Bougainvillea_sp.','Arisarum_vulgare',
          'Euonymus_japonicus','Ilex_perado_ssp._azorica','Magnolia_soulangeana','Buxus_sempervirens','Urtica_dioica',
          'Podocarpus_sp.','Acca_sellowiana','Hydrangea_sp.','Pseudosasa_japonica','Magnolia_grandiora',
           'Geranium_sp.','Aesculus_californica','Chelidonium_majus',
           'Schinus_terebinthifolius','Fragaria_vesca']
print (cm)

[[2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 

In [21]:
str_tree = export_graphviz(rfc1.estimators_[0], 
   out_file='tree.dot', 
   feature_names=X_train.columns, # column names
   class_names=True)

os.system('dot -Tpng tree.dot -o tree.png')
# Display in jupyter notebook
from IPython.display import Image
Image(filename = 'tree.png')

<class 'str'>
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36


FileNotFoundError: [Errno 2] No such file or directory: 'tree.png'

---